version: '3'
services:
  sofriki-cms:
    container_name: sofriki-cms
    build: .
    image: sofriki-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: sofriki-cmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      PUBLIC_URL: ${PUBLIC_URL}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
#    ports:
 #     - '1337:1337'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.friki-cms.rule=Host(`cms.friki.si`)"
      - "traefik.http.routers.friki-cms.entrypoints=https"
      - "traefik.http.routers.friki-cms.service=friki-cms"
      - "traefik.http.routers.friki-cms.tls.certresolver=cloudflare"
      - "traefik.http.services.friki-cms.loadbalancer.server.port=1337"
    networks:
      - proxy
    depends_on:
      - sofriki-cmsDB
      
  sofriki-cmsDB:
    container_name: sofriki-cmsDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - sofriki-cms-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

 #   ports:
#      - '5432:5432'
    networks:
      - proxy
      
volumes:
  sofriki-cms-data:

networks:
  proxy:
    external: true