version: '3'
services:
  sofriki-cms:
    container_name: sofriki-cms
    build: .
    # image: sofriki-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: sofriki-cmsDB
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - '1337:1337'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.friki-cms.rule=Host(`cms.friki.si`)'
      - 'traefik.http.routers.friki-cms.entrypoints=https'
      - 'traefik.http.routers.friki-cms.service=friki-cms'
      - 'traefik.http.routers.friki-cms.tls.certresolver=cloudflare'
      - 'traefik.http.services.friki-cms.loadbalancer.server.port=1337'
    networks:
      - proxy
    depends_on:
      - sofriki-cmsDB

  sofriki-cmsDB:
    container_name: sofriki-cmsDB
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - sofriki-cms-data:/var/lib/postgresql/data/
    networks:
      - proxy

volumes:
  sofriki-cms-data:

networks:
  proxy:
